#执行模板文件进行安装
- name: install yum-utils
  yum: name=yum-utils state=present

- name: install mysql yum repo centos6
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  shell: yum localinstall -y mysql-community-release-el6-5.noarch.rpm
  args:
    chdir: "{{ rpm_dir }}"

- name: install mysql yum repo centos7
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  shell: yum localinstall -y mysql-community-release-el7-5.noarch.rpm
  args:
    chdir: "{{ rpm_dir }}"

- name: install mysql5.6
  yum: name=mysql-community-server state=present

- name: enabled mysql service
  service: name=mysqld enabled=yes state=started

- name: install expect
  yum: name=expect state=present

- name: 修改Centos6下mysql默认密码并开启root远程登录
  script: centos6_mysql_user.sh
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

- name: 修改Centos7下mysql默认密码并开启root远程登录
  script: centos7_mysql_user.sh
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
